In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sns.set()

In [3]:
#Creating 2 * 2 matrix
matrix_1 = np.array([[2,3],
                     [6,7]])

print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
#Creating 3*3 matrix
matrix_2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
matrix_2.shape

(3, 3)

In [7]:
#Creating Random Matrix:

random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.06338625 0.28433975 0.16154818]
 [0.17381014 0.95125543 0.74449442]
 [0.12862062 0.46406345 0.20163022]]


In [8]:
random_integer_matrix = np.random.randint(100, size = (3,3))
print(random_integer_matrix)

[[34 65  4]
 [27 21 33]
 [12 77 33]]


In [9]:
#Creating matrix of ones:
one_matrix = np.ones((2,3), dtype= int)
print(one_matrix)

[[1 1 1]
 [1 1 1]]


In [10]:
#Creating null matrix:
zero_matrix = np.zeros((7,7), dtype = int)
print(zero_matrix)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [11]:
#Creating identity matrix:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#Transpose of matrix:
matrix = np.random.randint(100, size= (4,5))
print(matrix)
matrix_transpose = matrix.T
print(matrix_transpose)

[[ 0 18 16  5 47]
 [27 81 22 33 25]
 [ 7 13 12  6 42]
 [75 33 67 19  1]]
[[ 0 27  7 75]
 [18 81 13 33]
 [16 22 12 67]
 [ 5 33  6 19]
 [47 25 42  1]]


### Implementation of matrix operation

In [13]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [1,2],
    [3,4]
])

#Two Matrices of shame shape can be added
print(A.shape)
print(B.shape)

(2, 2)
(2, 2)


In [14]:
sum = A + B 
print(sum)

[[2 4]
 [6 8]]


In [15]:
#Alternate way of adding:
A = np.random.randint(10, size = (3,3))
B = np.random.randint(20, size = (3,3))

print(A)
print(B)

sum = np.add(A,B)
print(sum)

[[6 9 3]
 [5 0 8]
 [6 9 6]]
[[11 15  5]
 [ 8  2 18]
 [ 9  0  3]]
[[17 24  8]
 [13  2 26]
 [15  9  9]]


In [16]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [1,2],
    [3,4]
])

#Two Matrices of shame shape can be added
print(A.shape)
print(B.shape)

(2, 2)
(2, 2)


In [17]:
difference = A - B 
print(difference)

[[0 0]
 [0 0]]


In [18]:
#Alternate way of subtracting:
A = np.random.randint(10, size = (3,3))
B = np.random.randint(20, size = (3,3))

print(A)
print(B)

sum = np.subtract(A,B)
print(sum)

[[5 0 8]
 [3 9 6]
 [4 5 4]]
[[10  6 13]
 [ 2 13  7]
 [18 10  2]]
[[ -5  -6  -5]
 [  1  -4  -1]
 [-14  -5   2]]


In [19]:
#Multiplying by a scalar
S = 4
A = np.random.randint(20, size = (3,3))

print(A)

scalar_product = np.multiply(S,A)

print(scalar_product)

[[18  0  2]
 [ 5  1 10]
 [10 12 18]]
[[72  0  8]
 [20  4 40]
 [40 48 72]]


In [ ]:
#Multiplying matrix by a matrix (dot product)
A = np.random.randint(10, size= (3,4))
B = np.random.randint(5, size= (4,3))

print(A)
print(B)

product = np.dot(A,B)
print(product)
#Note: np.dot() gives the typical matrix product np.multiply() gives the element wise product

[[8 2 9 4]
 [5 5 2 2]
 [3 0 7 8]]
[[4 2 3]
 [3 0 0]
 [3 3 3]
 [1 0 0]]
[[69 43 51]
 [43 16 21]
 [41 27 30]]


In [ ]:
#Multiplying matrix by a matrix (elementwise)
A = np.random.randint(10, size= (3,3))
B = np.random.randint(5, size= (3,3))

print(A)
print(B)

product = np.multiply(A,B)
print(product)
#Note: np.dot() gives the typical matrix product np.multiply() gives the element wise product

[[1 1 6]
 [8 9 3]
 [0 3 1]]
[[1 1 2]
 [0 0 4]
 [4 3 0]]
[[ 1  1 12]
 [ 0  0 12]
 [ 0  9  0]]
